### ISSUE TITLE
Enable SBR and use the k8s lease

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-sample-cluster-kubernetes-scala#65]

**Comment by patriknw** [comment]
Sounds good to enable SBR but not with the k8 lease because that would make the https://doc.akka.io/docs/akka-management/current/kubernetes-deployment/index.html more complicated.

**Comment by ignasi35** [comment]
What is the relation between this sample and the k8s deployment guide in the Akka Management docs?

Plus, I don't think the deployment guide needs to be any more complicated. It's on the Akka Management docs already, so a final mention to "Have a look at the k8s lease section for ..." could be enough.

**Comment by patriknw** [comment]
It's the example that is referred to from that guide. The Java/Scala links on the page What is the relation between this sample and the k8s deployment guide in the Akka Management docs?

We should not promote the Kubernetes lease as the default way. Most people are already using keep-majority and we know from lack of issue reports that it's working well. We don't have much data points for the lease yet. There are tradeoffs so it's not clear that it's always better.
